language: node_js

node_js:
  - stable

services:
  - mongodb

cache:
  directories:
    - node_modules

env:
  global:
    - NODE_ENV = travis
    - DB_URI = mongodb://localhost:27017/onbvn-backend

install:
  - npm install
